CXXFLAGS = -Ieditor-core/include -Incurses-editor -Inoudar-core/include -Incurses-version -O2 -g -c -std=c++0x -ferror-limit=1 -Werror -Wall 
CXX = clang++

OBJS = ncurses-editor/main.o \
     editor-core/src/CEditor.o \
    ncurses-version/CConsoleRenderer.o \
    noudar-core/src/CActor.o \
    noudar-core/src/CKnight.o \
    noudar-core/src/CMonster.o \
    noudar-core/src/CMap.o \
    noudar-core/src/CElixirFountain.o \
    noudar-core/src/CDoorway.o \
    noudar-core/src/IFileLoaderDelegate.o \
    noudar-core/src/IMapElement.o \
    noudar-core/src/CGame.o \
    noudar-core/src/CPlainFileLoader.o \
    noudar-core/src/CGameDelegate.o \
    noudar-core/src/commands/CActorMeleeAttackCommand.o \
    noudar-core/src/commands/IGameCommand.o \
    noudar-core/src/commands/CMoveActorCommand.o \
    noudar-core/src/commands/CLoadNewLevelCommand.o \
    noudar-core/src/commands/CTurnActorCommand.o \
    noudar-core/src/commands/CQuitCommand.o \
    noudar-core/src/commands/CNullCommand.o \
    noudar-core/src/commands/CEndTurnCommand.o

LDFLAGS = -lncurses
TARGET = editor

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LDFLAGS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
	rm src/*~
	rm include/*~
	rm *~
