CXXFLAGS = -Inoudar-core/include -Incurses-version -O2 -g -c -std=c++0x  -march=i486
CXX = i586-pc-msdosdjgpp-g++

OBJS = ncurses-version/main.o \
    ncurses-version/TrivialConsoleRenderer.o \
    noudar-core/src/Vec2i.o \
    noudar-core/src/CActor.o \
    noudar-core/src/CMonster.o \
    noudar-core/src/CMonsterGenerator.o \
    noudar-core/src/CTeam.o \
    noudar-core/src/CMap.o \
    noudar-core/src/CHuntApproach.o \
    noudar-core/src/CCharacter.o \
    noudar-core/src/CCharacterArchetype.o \
    noudar-core/src/CDoorway.o \
    noudar-core/src/Common.o \
    noudar-core/src/IFileLoaderDelegate.o \
    noudar-core/src/IMapElement.o \
    noudar-core/src/CGame.o \
    noudar-core/src/CItem.o \
    noudar-core/src/CStorageItem.o \
    noudar-core/src/CPlainFileLoader.o \
    noudar-core/src/CGameDelegate.o \
    noudar-core/src/commands/CCycleNextItemCommand.o \
    noudar-core/src/commands/CCyclePreviousItemCommand.o \
    noudar-core/src/commands/IGameCommand.o \
    noudar-core/src/commands/CMoveActorCommand.o \
    noudar-core/src/commands/CLoadNewLevelCommand.o \
    noudar-core/src/commands/CTurnActorCommand.o \
    noudar-core/src/commands/CQuitCommand.o \
    noudar-core/src/commands/CDropItemCommand.o \
    noudar-core/src/commands/CPickItemCommand.o \
    noudar-core/src/commands/CNullCommand.o \
    noudar-core/src/commands/CUseCurrentItemCommand.o \
    noudar-core/src/commands/CEndTurnCommand.o



TARGET = NOUDAR.exe

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LDFLAGS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
	rm src/*~
	rm include/*~
	rm *~
