site_name: Dungeons of Noudar (core)
repo_url: https://github.com/TheFakeMontyOnTheRun/noudar-core
theme: readthedocs
pages:
- Index: index.md
- Items: items.md
- Levels: levels.md
- Locations: locations.md
- Church: church.md
- Monastery: monastery.md
- Cemetery: cemetery.md
- The Nest: nest.md
- Prison: prison.md
- Patium: patium.md
- Mausoleum: mausoleum.md
- Characters: characters.md
- crossbow.md
- Demon: demon.md
- Master demon: master-demon.md
- Monks: monks.md
- Prison: prison.md
- Shield: shield.md
- Statue: statue.md
- Tower: tower.md
- Vitrals: vitrals.md
- Warthog: warthog.md
- Tokens of faith: tokens-of-faith.md
- The citadel: citadel.md
- Bell tower: bell-tower.md